name: MorphVasion
version: '${project.version}'
main: hobby.servah.morphvasion.MorphVasion
api-version: 1.19
commands:
  start:
    description: Allows players to start the game (skip the lobby phase) either via the /start command or the Redstone Dust in their inventories. This command takes no arguments.
    aliases: [s]
    usage: /start
    permission: morphvasion.start
  setplayerspawn:
    description: Sets the player spawn point for the current map
    usage: /setplayerspawn
    permission: morphvasion.setPlayerSpawn
permissions:
  morphvasion.*:
    description: Wildcard permission --> all permissions concerning this plugin
    children:
      #TODO add all the other permissions
      morphvasion.start: true
  morphvasion.start:
    description: Allows players to start the game (skip the lobby phase) either via the /start command or the Redstone Dust in their inventories. (Read more with "/help start")
  morphvasion.setPlayerSpawn:
    description: Allows players to execute the /setplayerspawn command